import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const base = process.env.SIMULATOR_BASE_URL ?? 'http://localhost:4173';
const output = 'tmp/instructor-requirements';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
const checks = [];
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 1000 } });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto(base + '/simulate');
  await page.waitForFunction(() => document.documentElement.dataset.appReady === 'true');
  assert.equal(await page.locator('[data-theory-volume]').textContent(), '25,00 mL');
  assert.ok((await page.locator('[data-theory]').boundingBox()).y < (await page.locator('#run-simulation').boundingBox()).y, 'Theory precedes the run control');
  assert.equal(await page.locator('#run-simulation').isDisabled(), true);
  const calculate = () => page.getByRole('button', { name: 'Tính trạng thái', exact: true }).click();
  const volume = async () => Number.parseFloat(await page.locator('[data-result="added-volume"]').textContent());
  const stage = page.locator('[data-vessel-3d]');
  const canvas = page.locator('[data-vessel-viewport] canvas');
  await calculate(); await stage.scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('[data-vessel-3d]').dataset.renderer === 'ready');
  assert.equal(await page.locator('[data-theory-ph]').textContent(), '7,00 (trung tính) · 25 °C');
  assert.match(await page.locator('[data-theory-moles]').textContent(), /0.025 L = 0,00250000 mol/);
  assert.equal(await page.locator('[data-theory-reaction]').textContent(), 'HCl + NaOH → NaCl + H₂O');
  checks.push('25 mL theory visible before running');
  await page.locator('#analyte-concentration').fill('0.2');
  await page.locator('#analyte-volume').fill('20');
  assert.equal(await page.locator('[data-theory]').getAttribute('data-status'), 'stale');
  assert.equal(await page.locator('#run-simulation').isDisabled(), true);
  await calculate(); assert.equal(await page.locator('[data-theory-volume]').textContent(), '40,00 mL');
  const ticks = await page.locator('.axis-tick-x text').allTextContents();
  assert.deepEqual(ticks, ['0', '20', '40', '60', '80']);
  checks.push('input change invalidates theory, recalculates 40 mL and 80 mL axis');
  await page.locator('#case-selector').selectOption('hcl-naoh-initial'); await calculate();
  await page.locator('#simulation-speed').selectOption('fast');
  const assertReset = async (capacity = '50.00') => {
    await page.getByRole('button', { name: 'Reset thí nghiệm', exact: true }).click();
    assert.equal(await volume(), 0); assert.equal(await canvas.getAttribute('data-buret-ml'), capacity);
    assert.equal(await canvas.getAttribute('data-total-ml'), '25.00');
    assert.equal(await canvas.getAttribute('data-drop-count'), '0');
    assert.equal(await page.locator('[data-result="ph"]').textContent(), '1.00');
    assert.equal(await page.locator('[data-curve-rows] tr').count(), 1);
    assert.equal(await page.locator('#analyte-concentration').inputValue(), '0.1');
    assert.equal(await page.locator('#analyte-volume').inputValue(), '25');
    assert.equal(await page.locator('#simulation-speed').inputValue(), 'fast');
    await page.waitForTimeout(2700);
    assert.equal(await volume(), 0); assert.equal(await canvas.getAttribute('data-active-drops'), '0');
    assert.equal(await page.locator('.indicator-transient').count(), 0);
    assert.equal(await page.locator('#run-simulation').isEnabled(), true);
  };
  await page.locator('#run-simulation').click();
  await page.waitForFunction(() => parseFloat(document.querySelector('[data-result="added-volume"]').textContent) > 0);
  const runningVolume = await volume();
  await page.locator('#chart-style').selectOption('line');
  await page.waitForFunction((previous) => parseFloat(document.querySelector('[data-result="added-volume"]').textContent) > previous, runningVolume);
  assert.equal(await page.locator('#pause-simulation').isEnabled(), true);
  assert.equal(await page.locator('polyline.curve-line').count(), 1);
  await assertReset(); checks.push('reset during run cancels pending steps and effects');
  await page.locator('#run-simulation').click();
  await page.waitForFunction(() => parseFloat(document.querySelector('[data-result="added-volume"]').textContent) > 0);
  await page.locator('#pause-simulation').click(); await assertReset(); checks.push('reset while paused');
  await page.locator('#buret-volume').fill('0.2'); await calculate();
  await page.locator('#run-simulation').click();
  await page.waitForFunction(() => document.querySelector('[data-result="added-volume"]').textContent === '0.20 mL' && document.querySelector('#pause-simulation').disabled);
  await assertReset('0.20'); checks.push('reset after completion refills selected buret');
  await page.locator('#case-selector').selectOption('hcl-naoh-equivalence'); await calculate();
  await assertReset(); checks.push('reset nonzero sample starts at zero');
  await page.evaluate(() => { for (let i = 0; i < 251; i += 1) document.querySelector('#add-drop').click(); });
  const before = await page.locator('[data-curve-rows]').innerHTML(); const oldVolume = await volume();
  await page.locator('#chart-style').selectOption('line');
  assert.equal(await page.locator('polyline.curve-line').count(), 1);
  const points = await page.locator('polyline.curve-line').getAttribute('points');
  assert.equal(points.split(' ').length, 252);
  const actualPoints = await page.locator('[data-chart-point="Mô phỏng"]').evaluateAll((elements) => elements.map((e) => `${e.getAttribute('cx')},${e.getAttribute('cy')}`).join(' '));
  assert.equal(points, actualPoints);
  assert.equal(await page.evaluate(async () => {
    const { validatePassiveGraphSvg } = await import('/src/ui/htmlSafety.js');
    return validatePassiveGraphSvg(document.querySelector('[data-chart]').outerHTML);
  }), true, 'Line chart remains exportable with axes and tooltips');
  await page.locator('#chart-style').selectOption('points');
  assert.equal(await page.locator('polyline.curve-line').count(), 0);
  assert.equal(await volume(), oldVolume); assert.equal(await page.locator('[data-curve-rows]').innerHTML(), before);
  assert.deepEqual(await page.locator('.axis-tick-y text').allTextContents(), ['0', '2', '4', '6', '8', '10', '12', '14']);
  assert.equal(await page.locator('.axis-label-x').textContent(), 'V NaOH đã thêm (mL)');
  await page.locator('[data-chart-point="Mô phỏng"]').last().hover();
  assert.match(await page.locator('[data-chart-readout]').textContent(), /V = 25.1000 mL; pH = 10.3002/);
  await page.locator('[data-chart-point="Mô phỏng"]').last().focus();
  assert.match(await page.locator('[data-chart-readout]').textContent(), /V = 25.1000 mL; pH = 10.3002/);
  checks.push('line connects exact history points without smoothing; switching preserves state/history; axes/readout');
  for (const system of ['weak-acid-strong-base', 'strong-acid-weak-base']) {
    await page.locator('#system-type').selectOption(system); await calculate();
    const theoryPh = Number.parseFloat((await page.locator('[data-theory-ph]').textContent()).replace(',', '.'));
    assert.ok(system === 'weak-acid-strong-base' ? theoryPh > 7 : theoryPh < 7);
    await page.locator('#add-drop').click(); assert.equal(await volume(), 0.1);
    assert.equal(await canvas.getAttribute('data-total-ml'), '25.10');
    assert.equal(await page.locator('[data-curve-rows] tr:last-child td:nth-child(2)').textContent(), await page.locator('[data-result="ph"]').textContent());
    await page.locator('#reset-simulation').click(); assert.equal(await volume(), 0);
    if (system === 'strong-acid-weak-base') assert.equal(await page.locator('.axis-label-x').textContent(), 'V HCl đã thêm (mL)');
  }
  checks.push('weak systems: non-neutral equivalence, correct titrant volume, chart/model/reset');
  await page.locator('#case-selector').selectOption('hcl-naoh-initial'); await calculate();
  await page.locator('#add-drop').click(); await page.locator('#chart-style').selectOption('line');
  for (const width of [320, 375, 430, 768, 1366, 1920]) {
    await page.setViewportSize({ width, height: 1000 }); await page.waitForTimeout(250);
    const layout = await page.evaluate(() => {
      const svg = document.querySelector('[data-chart]'); const bound = svg.getBoundingClientRect();
      const texts = [...svg.querySelectorAll('text')];
      const contained = texts.every((e) => { const box = e.getBoundingClientRect(); return box.left >= bound.left - 1 && box.right <= bound.right + 1 && box.top >= bound.top - 1 && box.bottom <= bound.bottom + 1; });
      const x = [...svg.querySelectorAll('.axis-tick-x text')].map((e) => e.getBoundingClientRect());
      const title = svg.querySelector('.axis-label-y').getBoundingClientRect();
      const topTick = svg.querySelector('.axis-tick-y:last-of-type text')?.getBoundingClientRect() ?? [...svg.querySelectorAll('.axis-tick-y text')].at(-1).getBoundingClientRect();
      return { overflow: document.documentElement.scrollWidth > innerWidth, contained, nonoverlap: x.every((box, i) => i === 0 || box.left > x[i - 1].right) && title.bottom < topTick.top };
    });
    assert.deepEqual(layout, { overflow: false, contained: true, nonoverlap: true }, `axes at ${width}px`);
  }
  await page.setViewportSize({ width: 1366, height: 1000 });
  await page.screenshot({ path: output + '/desktop.png', fullPage: true });
  const mobile = await browser.newPage({ viewport: { width: 375, height: 900 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', (e) => errors.push(e.message));
  await mobile.goto(base + '/simulate');
  await mobile.getByRole('button', { name: 'Tính trạng thái', exact: true }).click();
  await mobile.locator('#add-drop').click(); await mobile.locator('#chart-style').selectOption('line');
  await mobile.locator('[data-chart-point="Mô phỏng"]').last().tap();
  assert.match(await mobile.locator('[data-chart-readout]').textContent(), /V = 0.1000 mL; pH = 1.0035/);
  await mobile.locator('.graph-panel').screenshot({ path: output + '/mobile-chart.png' });
  await mobile.locator('[data-theory]').screenshot({ path: output + '/mobile-theory.png' });
  checks.push('six responsive widths and real touch readout');
  assert.deepEqual(errors, []);
  await writeFile(output + '/results.json', JSON.stringify({ checks, errors }, null, 2));
  console.log(JSON.stringify({ passed: checks.length, checks, errors }, null, 2));
} finally { await browser.close(); }
