// Run with a local server: node tests/vessel3d.browser.mjs
// PLAYWRIGHT_MODULE can point to an isolated QA installation outside the repo.
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const output = resolve('tmp/vessel3d-qa');
const baseUrl = process.env.SIMULATOR_BASE_URL ?? 'http://localhost:4173';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 1000 } });
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`${baseUrl}/simulate`);
  const stage = page.locator('[data-vessel-3d]');
  await stage.scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('[data-vessel-3d]').dataset.renderer === 'ready');
  assert.equal(await page.locator('[data-chart-empty]').isVisible(), true);
  await page.getByRole('button', { name: 'Tính trạng thái', exact: true }).click();
  assert.equal(await page.locator('[data-chart-empty]').isVisible(), false, 'Placeholder is hidden when the curve has data');
  await stage.scrollIntoViewIfNeeded();
  const canvas = stage.locator('canvas');
  assert.equal(await canvas.getAttribute('data-buret-ml'), '50.00');
  await page.getByRole('button', { name: 'Thêm giọt 0,10 mL', exact: true }).click();
  assert.equal(await canvas.getAttribute('data-drop-count'), '1');
  assert.equal(await canvas.getAttribute('data-buret-ml'), '49.90');
  assert.equal(await stage.locator('[data-vessel-total]').textContent(), (Number(await canvas.getAttribute('data-total-ml')).toFixed(2).replace('.', ',') + ' mL'));
  await stage.scrollIntoViewIfNeeded();
  await page.waitForTimeout(1100);
  await stage.screenshot({ path: `${output}/desktop.png` });
  const initialCamera = await canvas.screenshot();
  const box = await canvas.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 120, box.y + box.height / 2 + 50, { steps: 16 });
  await page.mouse.up();
  await page.waitForTimeout(800);
  const rotatedCamera = await canvas.screenshot();
  assert.ok(!rotatedCamera.equals(initialCamera), 'Dragging changes the rendered camera');
  await page.mouse.wheel(0, -300);
  await page.waitForTimeout(500);
  const zoomedCamera = await canvas.screenshot();
  assert.ok(!zoomedCamera.equals(rotatedCamera), 'Wheel zoom changes the rendered camera');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down({ button: 'right' });
  await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 - 30, { steps: 8 });
  await page.mouse.up({ button: 'right' });
  await page.waitForTimeout(500);
  assert.ok(!(await canvas.screenshot()).equals(zoomedCamera), 'Right drag pans the camera');
  await page.getByRole('button', { name: 'Đặt lại góc nhìn camera' }).click();
  await page.waitForTimeout(800);
  const resetCamera = await canvas.screenshot();
  const pixelError = await page.evaluate(async ([before, after]) => {
    const pixels = async (encoded) => {
      const img = new Image();
      img.src = `data:image/png;base64,${encoded}`;
      await img.decode();
      const surface = document.createElement('canvas');
      surface.width = img.width;
      surface.height = img.height;
      const context = surface.getContext('2d');
      context.drawImage(img, 0, 0);
      return context.getImageData(0, 0, img.width, img.height).data;
    };
    const a = await pixels(before);
    const b = await pixels(after);
    let difference = 0;
    for (let i = 0; i < a.length; i += 1) difference += Math.abs(a[i] - b[i]);
    return difference / a.length;
  }, [initialCamera.toString('base64'), resetCamera.toString('base64')]);
  assert.ok(pixelError < 0.5, `Camera reset restores the view (mean pixel error ${pixelError})`);
  await page.locator('#simulation-speed').selectOption('fast');
  await page.getByRole('button', { name: 'Chạy tự động', exact: true }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Tạm dừng', exact: true }).click();
  const pausedDrops = await canvas.getAttribute('data-drop-count');
  assert.ok(Number(pausedDrops) > 1);
  await page.waitForTimeout(700);
  assert.equal(await canvas.getAttribute('data-drop-count'), pausedDrops);
  const pausedPh = await page.locator('[data-result="ph"]').textContent();
  assert.equal((await stage.locator('[data-vessel-ph]').textContent()).replace(',', '.'), pausedPh);
  assert.equal(await page.locator('[data-curve-rows] tr:last-child td:nth-child(2)').textContent(), pausedPh);
  await page.getByRole('button', { name: 'Đặt lại trạng thái', exact: true }).click();
  assert.equal(await canvas.getAttribute('data-drop-count'), '0');
  assert.equal(await canvas.getAttribute('data-buret-ml'), '50.00');
  // Drive actual UI steps through and past equivalence; solver/chart remain authoritative.
  await page.evaluate(() => { for (let i = 0; i < 260; i += 1) document.querySelector('#add-drop').click(); });
  assert.equal(await canvas.getAttribute('data-indicator'), 'base-excess');
  assert.equal(await canvas.getAttribute('data-drop-count'), '260');
  assert.ok(Number(await page.locator('[data-result="ph"]').textContent()) > 10);
  assert.equal(await page.locator('[data-curve-rows] tr').count(), 261);
  await stage.scrollIntoViewIfNeeded();
  await page.waitForTimeout(1100);
  await stage.screenshot({ path: `${output}/pink.png` });
  await page.locator('.simulation-layout').screenshot({ path: `${output}/two-columns.png` });
  const history = page.locator('.curve-table');
  assert.ok(await history.evaluate((element) => element.scrollHeight > element.clientHeight), 'History scrolls without growing the chart panel');
  for (const width of [320, 375, 430, 768, 1023, 1024, 1366, 1920]) {
    await page.setViewportSize({ width, height: 1000 });
    await stage.scrollIntoViewIfNeeded();
    await page.waitForTimeout(150);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No overflow at ${width}px`);
    const left = await page.locator('.experiment-panel').boundingBox();
    const right = await page.locator('.graph-panel').boundingBox();
    if (width >= 1024) {
      assert.ok(right.x > left.x + left.width, `3D left / chart right at ${width}px`);
      assert.ok(Math.abs(left.y - right.y) < 1 && Math.abs(left.height - right.height) < 1, `Balanced columns at ${width}px`);
      const workspace = await page.locator('#main-content').boundingBox();
      assert.ok(workspace.width >= Math.min(1560, width - 48) - 1, 'Uses available desktop width');
    } else {
      assert.ok(right.y >= left.y + left.height, `Vertical layout at ${width}px`);
    }
    const chartSizing = await page.locator('[data-chart]').evaluate((svg) => ({ box: svg.viewBox.baseVal.height, pixels: svg.clientHeight }));
    assert.ok(Math.abs(chartSizing.box - chartSizing.pixels) < 1, 'Chart follows viewport size');
  }
  await page.setViewportSize({ width: 1366, height: 1000 });
  await page.locator('#titration-form').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${output}/workspace-desktop.png`, fullPage: true });
  const mobile = await browser.newPage({ viewport: { width: 375, height: 900 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
  mobile.on('pageerror', (error) => errors.push(error.message));
  await mobile.goto(`${baseUrl}/simulate`);
  const mobileStage = mobile.locator('[data-vessel-3d]');
  await mobileStage.scrollIntoViewIfNeeded();
  await mobile.waitForFunction(() => document.querySelector('[data-vessel-3d]').dataset.renderer === 'ready');
  await mobileStage.screenshot({ path: `${output}/mobile.png` });
  const mobileCanvas = mobileStage.locator('canvas');
  const initialTouch = await mobileCanvas.screenshot();
  const mobileBox = await mobileCanvas.boundingBox();
  const touchX = mobileBox.x + mobileBox.width / 2;
  const touchY = mobileBox.y + mobileBox.height / 2;
  const cdp = await mobile.context().newCDPSession(mobile);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchX, y: touchY, id: 1 }] });
  for (let i = 1; i <= 8; i += 1) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchX + i * 8, y: touchY, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await mobile.waitForTimeout(700);
  const rotatedTouch = await mobileCanvas.screenshot();
  assert.ok(!rotatedTouch.equals(initialTouch), 'One finger rotates on mobile');
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchX - 25, y: touchY, id: 1 }, { x: touchX + 25, y: touchY, id: 2 }] });
  for (let i = 1; i <= 6; i += 1) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchX - 25 - i * 4, y: touchY + i * 3, id: 1 }, { x: touchX + 25 + i * 4, y: touchY + i * 3, id: 2 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await mobile.waitForTimeout(700);
  assert.ok(!(await mobileCanvas.screenshot()).equals(rotatedTouch), 'Two fingers zoom/pan on mobile');
  await cdp.detach();
  await mobile.getByRole('button', { name: 'Tính trạng thái', exact: true }).click();
  await mobile.getByRole('button', { name: 'Thêm giọt 0,10 mL', exact: true }).click();
  assert.equal(await mobileCanvas.getAttribute('data-drop-count'), '1');
  const mobilePh = await mobile.locator('[data-result="ph"]').textContent();
  assert.equal(await mobile.locator('[data-curve-rows] tr:last-child td:nth-child(2)').textContent(), mobilePh, 'Mobile chart and chemistry use the same result');
  // Capture panels separately: WebGL intentionally stops drawing off-screen.
  await mobile.locator('.experiment-panel').scrollIntoViewIfNeeded();
  await mobile.waitForTimeout(250);
  await mobile.locator('.experiment-panel').screenshot({ path: `${output}/workspace-mobile.png` });
  await mobile.locator('.graph-panel').scrollIntoViewIfNeeded();
  await mobile.locator('.graph-panel').screenshot({ path: `${output}/workspace-mobile-chart.png` });
  // Changing cases invalidates the previous 3D chemistry/color just as the chart.
  await page.locator('#case-selector').selectOption({ index: 1 });
  assert.equal(await canvas.getAttribute('data-drop-count'), '0');
  assert.equal(await canvas.getAttribute('data-indicator'), 'idle');
  assert.equal(await stage.locator('[data-vessel-ph]').textContent(), '—');
  assert.equal(await page.locator('[data-chart-empty]').isVisible(), true, 'Case change restores the empty chart state');
  await page.getByRole('link', { name: 'Thư viện ca', exact: true }).click();
  const homeWidth = await page.locator('#main-content').evaluate((element) => element.clientWidth);
  assert.equal(homeWidth, 1180, 'Home retains its original container width');
  const fallback = await browser.newPage();
  await fallback.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { return type.startsWith('webgl') ? null : original.call(this, type, ...args); }; });
  await fallback.goto(`${baseUrl}/simulate`);
  await fallback.locator('[data-vessel-3d]').scrollIntoViewIfNeeded();
  await fallback.waitForFunction(() => document.querySelector('[data-vessel-3d]').dataset.renderer === 'fallback');
  await fallback.getByRole('button', { name: 'Tính trạng thái', exact: true }).click();
  await fallback.getByRole('button', { name: 'Thêm giọt 0,10 mL', exact: true }).click();
  assert.equal(await fallback.locator('[data-result="added-volume"]').textContent(), '0.10 mL');
  assert.deepEqual(errors, []);
  console.log('3D/layout browser PASS: state/drop/run/pause/reset, color/chart, camera/touch, 8 widths, balanced columns, chart resize, scrollable history and fallback.');
  console.log(`Screenshots: ${output}`);
} finally { await browser.close(); }
