export const PHASE_4_PH_TOLERANCE = 0.02;

// Fixed values from the hand/reference table, rounded to four decimal places.
// They are never generated by the website solver during a test.
export const phase4Nh3HclReference = Object.freeze([
  Object.freeze({ id: 'NH3-HCl-REF-01-initial', label: 'Standard initial', Ca: 0.1, Va: 0, Cb: 0.1, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 11.1247, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-01-half', label: 'Standard half equivalence', Ca: 0.1, Va: 0.0125, Cb: 0.1, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 9.2548, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-01-equivalence', label: 'Standard equivalence', Ca: 0.1, Va: 0.025, Cb: 0.1, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 5.2781, stage: 'at-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-01-after', label: 'Standard after equivalence', Ca: 0.1, Va: 0.02525, Cb: 0.1, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 3.3031, stage: 'after-equivalence', excessSpecies: 'H+' }),
  Object.freeze({ id: 'NH3-HCl-REF-01-excess', label: 'Standard large excess', Ca: 0.1, Va: 0.05, Cb: 0.1, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 1.4771, stage: 'after-equivalence', excessSpecies: 'H+' }),
  Object.freeze({ id: 'NH3-HCl-REF-02-initial', label: 'Different concentration initial', Ca: 0.02, Va: 0, Cb: 0.01, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 10.6184, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-02-half', label: 'Different concentration half equivalence', Ca: 0.02, Va: 0.00625, Cb: 0.01, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 9.2514, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-02-equivalence', label: 'Different concentration equivalence', Ca: 0.02, Va: 0.0125, Cb: 0.01, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 5.7152, stage: 'at-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-02-after', label: 'Different concentration after equivalence', Ca: 0.02, Va: 0.01275, Cb: 0.01, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 3.8779, stage: 'after-equivalence', excessSpecies: 'H+' }),
  Object.freeze({ id: 'NH3-HCl-REF-02-excess', label: 'Different concentration large excess', Ca: 0.02, Va: 0.025, Cb: 0.01, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 2.301, stage: 'after-equivalence', excessSpecies: 'H+' }),
  Object.freeze({ id: 'NH3-HCl-REF-03-dilute-initial', label: 'Dilute-model boundary initial', Ca: 1e-6, Va: 0, Cb: 1e-6, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 7.9822, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-03-dilute-half', label: 'Dilute-model boundary half equivalence', Ca: 1e-6, Va: 0.0125, Cb: 1e-6, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 7.5432, stage: 'before-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-03-dilute-equivalence', label: 'Dilute-model boundary equivalence', Ca: 1e-6, Va: 0.025, Cb: 1e-6, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 6.9941, stage: 'at-equivalence', excessSpecies: null }),
  Object.freeze({ id: 'NH3-HCl-REF-03-dilute-after', label: 'Dilute-model boundary after equivalence', Ca: 1e-6, Va: 0.02525, Cb: 1e-6, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 6.9835, stage: 'after-equivalence', excessSpecies: 'H+' }),
  Object.freeze({ id: 'NH3-HCl-REF-03-dilute-excess', label: 'Dilute-model boundary large excess', Ca: 1e-6, Va: 0.05, Cb: 1e-6, Vb: 0.025, Kb: 1.8e-5, temperature: 298.15, pH: 6.4419, stage: 'after-equivalence', excessSpecies: 'H+' }),
]);
